version: 0.2

phases:
  install:
    commands:
      - echo Instalando dependências...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Fase de build concluída com sucesso!

artifacts:
  files:
    - '**/*'
